### ISSUE TITLE
About I frame

### ISSUE THREAD

**Issue by hhuyujie** [binzzheng/DVC-PyTorch#2]
In the official implementation, the I frame is used by the learning-based image compression algorithm (Ballé et al). Why do you change it to H.265?

**Comment by binzzheng** [comment]
In fact, there are many open source implementations of DVC, not all of them follow the settings of the original paper. For example, [OpenDVC](https://github.com/RenYang-home/OpenDVC) uses BPG to compress I frame. Here just use H265 to compress the I frame and get the performance as reported in the paper. In theory, you can use balle's learning-based I-frame compression algorithm to jointly optimize the whole learning framework to achieve better performance.

**Comment by hhuyujie** [comment]
> 

Thanks very much for your detailed answer!
