### ISSUE TITLE
模块导入问题

### ISSUE THREAD

**Issue by zkqby** [binzzheng/DVC-PyTorch#4]
### 作者您好，我最近在跑您开源的这个代码，目前遇到一个问题：
在subnet/_init_.py文件中：
from .entropy_params import *
from .context import *
from .feature_convert import *
from .offset_process import *
from .fvc_compression import *
这几个导入没有相应模块呢？请问是怎么回事儿呢？

**Comment by binzzheng** [comment]
你可以直接注释掉它，对代码应该是没有影响的，这是我之前做FVC实验时修改的代码，没有删除干净

**Comment by zkqby** [comment]
好的，谢谢！

> 你可以直接注释掉它，对代码应该是没有影响的，这是我之前做FVC实验时修改的代码，没有删除干净
